version: '3'
services:
  app:
    build: .
    container_name: axcel-app
    volumes:
      - ./y_db:/app/y_db
    ports:
      - 8080:8080
    env_file:
      - .env.local
    
  db:
    image: postgres:15.3-alpine
    container_name: axcel-db
    volumes:
      #- "./db_data/init:/docker-entrypoint-initdb.d"
      - "postgres_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: webapp
      POSTGRES_DB: webapp
volumes:
  postgres_db: